(library
 (name digestif)
 (public_name digestif)
 (modules digestif)
 (wrapped false)
 (virtual_modules digestif)
 (default_implementation digestif.c)
 (libraries eqaf))

; Also expose the installed C header when Digestif is built in a duniverse.
(rule
 (targets digestif_sha512.h)
 (deps ../src-c/native/sha512.h)
 (action (copy %{deps} %{targets})))

(rule
 (targets digestif_sha1.h)
 (deps ../src-c/native/sha1.h)
 (action (copy %{deps} %{targets})))

(rule
 (targets digestif_sha256.h)
 (deps ../src-c/native/sha256.h)
 (action (copy %{deps} %{targets})))
